[project]
name = 'New-Year-Resolution-Forensic-Analysis-Suite'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.gym-membership-guilt-accumulation-calculator]
path = 'contracts/gym-membership-guilt-accumulation-calculator.clar'
clarity_version = 3
epoch = 'latest'

[contracts.resolution-autopsy-timeline-reconstructor]
path = 'contracts/resolution-autopsy-timeline-reconstructor.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
